apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rjwu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-rjwu@sha256:b8ce7093922b82afd4abca55ef523de3830c393e036084d8874ef5ab0ab9a6e1
        name: my-nodejs
        resources: {}
status: {}
